language: python
python:
  - 3.8
before_install:
  - python --version
  - pip install -r requirements.txt
  - pip install -r requirements-travis.txt
  - export PYTHONPATH="${PYTHONPATH}:backup_server"
script: pytest tests
after_success:
  - pytest --cov=. tests/
  - coveralls